# -*- mode: python ; coding: utf-8 -*-

EXCLUDED_MODULES = [
    # WebEngine (Chromium) - 约 645MB
    'PySide6.QtWebEngine',
    'PySide6.QtWebEngineCore',
    'PySide6.QtWebEngineWidgets',
    'PySide6.QtWebEngineQuick',
    'PySide6.QtWebChannel',
    # 3D 相关
    'PySide6.Qt3DCore',
    'PySide6.Qt3DRender',
    'PySide6.Qt3DInput',
    'PySide6.Qt3DLogic',
    'PySide6.Qt3DExtras',
    'PySide6.Qt3DAnimation',
    'PySide6.QtQuick3D',
    # PDF
    'PySide6.QtPdf',
    'PySide6.QtPdfWidgets',
    # 其他不需要的模块
    'PySide6.QtBluetooth',
    'PySide6.QtNfc',
    'PySide6.QtPositioning',
    'PySide6.QtLocation',
    'PySide6.QtSensors',
    'PySide6.QtSerialPort',
    'PySide6.QtMultimedia',
    'PySide6.QtMultimediaWidgets',
    'PySide6.QtRemoteObjects',
    'PySide6.QtSql',
    'PySide6.QtTest',
    'PySide6.QtXml',
    'PySide6.QtDesigner',
    'PySide6.QtHelp',
    'PySide6.QtCharts',
    'PySide6.QtDataVisualization',
    'PySide6.QtGraphs',
    'PySide6.QtNetworkAuth',
    'PySide6.QtQuickWidgets',
    'PySide6.QtSpatialAudio',
    'PySide6.QtStateMachine',
    'PySide6.QtTextToSpeech',
    'PySide6.QtHttpServer',
]

a = Analysis(
    ['../main.py'],
    pathex=[],
    binaries=[],
    datas=[('../src/layout', './src/layout'), ('../config.yaml.default', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=EXCLUDED_MODULES,
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='semi-utils',
    icon='../logo.ico',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
